# Generated by Django 5.2.6 on 2025-09-17 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="frame_color",
            new_name="frame_colour",
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("store", "name", "frame_colour", "size")},
        ),
    ]
