# Generated by Django 5.2.6 on 2025-09-18 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_product_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="buyer",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="order",
            name="email_sent",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="frame_colour",
            field=models.CharField(default="black", max_length=20),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.CharField(default="medium", max_length=20),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.product",
            ),
        ),
    ]
