# Generated by Django 5.2.6 on 2025-09-21 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_category_options_remove_order_total_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("store", "name")},
        ),
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="frame_colour",
            field=models.CharField(
                choices=[
                    ("Black", "Black"),
                    ("Oak", "Oak"),
                    ("Silver", "Silver"),
                    ("White", "White"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.product"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="size",
            field=models.CharField(
                choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")], max_length=2
            ),
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "small_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "medium_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "large_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="shop.product",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="frame_colour",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
    ]
