# Generated by Django 5.2.6 on 2025-10-08 02:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_address_unique_default_shipping_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="address",
            name="unique_default_shipping",
        ),
        migrations.RemoveConstraint(
            model_name="address",
            name="unique_default_billing",
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                fields=("user", "is_shipping"), name="unique_shipping_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                fields=("user", "is_billing"), name="unique_billing_per_user"
            ),
        ),
    ]
