# Generated by Django 5.2.6 on 2025-10-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_remove_address_unique_default_shipping_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
    ]
