# Generated by Django 5.2.6 on 2025-10-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_product_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
    ]
